version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  buildAndTest:
    docker:
      - image: cimg/openjdk:21.0.0

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      - run: gradle dependencies
      - run: gradle test
      - codecov/upload

workflows:
  validate:
    jobs:
      - buildAndTest